extensions:
  basicauth/openobserve:
    client_auth:
      username: ${env:ZO_ROOT_USER_EMAIL}
      password: ${env:ZO_ROOT_USER_PASSWORD}

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 128
    spike_limit_mib: 32
  batch:
    timeout: 5s
    send_batch_size: 256

exporters:
  otlp_http/openobserve:
    endpoint: http://openobserve:5080/api/default
    auth:
      authenticator: basicauth/openobserve
    headers:
      stream-name: default
    timeout: 10s

service:
  extensions:
    - basicauth/openobserve
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp_http/openobserve]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp_http/openobserve]
